#!/bin/bash

_dropbox() {
    COMPREPLY=()
    prev="${COMP_WORDS[COMP_CWORD-1]}"
    curr="${COMP_WORDS[COMP_CWORD]}"

    commands="status help puburl stop running start filestatus ls autostart exclude lansync"

    if [ $COMP_CWORD -eq 1 ]; then
        COMPREPLY=( $(compgen -W "${commands}" -- "${curr}" ) )
    elif [ $COMP_CWORD -eq 2 ]; then
        case $prev in
            puburl | filestatus | ls | exclude )
                COMPREPLY=( $(compgen -W "$(ls)" -- "${curr}") )
                ;;
            help )
                COMPREPLY=( $(compgen -W "${commands}" -- "${curr}" ) )
                ;;
            * )
                ;;
        esac
    fi
}
complete -F _dropbox dropbox

_pip() {
    local curr="${COMP_WORDS[COMP_CWORD]}"
    local commands="install uninstall freeze list show search zip unzip bundle help"

    COMPREPLY=()
    [[ $COMP_CWORD -eq 1 ]] && {
        COMPREPLY=( $(compgen -W "${commands}" -- "${curr}") )
    } || {
        COMPREPLY=( $(compgen -f -- "${curr}") )
    }
}
complete -F _pip pip

_t() {
  local options=$(ls /opt/code)
  local current="${COMP_WORDS[COMP_CWORD]}"
  COMPREPLY=( $(compgen -W "${options}" -- "${current}") )
}
complete -F _t t
