#!/bin/bash

_update_ps1() {
    # PS1="$(powerline-shell.py --cwd-mode plain --mode flat $?)"
    PS1="$(powerline-shell $?)"
}

if [ "$TERM" != "linux" ]; then
    PROMPT_COMMAND=_update_ps1
fi


echo -ne "\033]12;red\007"
