" Buck's vimrc
" ------------

set nocompatible


call plug#begin('~/.vim/plugged')

" General utility library that other things depend on
Plug 'vim-scripts/L9'
Plug 'tpope/vim-commentary'
Plug 'jlanzarotta/bufexplorer'
Plug 'scrooloose/nerdtree'
Plug 'SirVer/ultisnips'
Plug 'honza/vim-snippets'
Plug 'kien/ctrlp.vim'

Plug 'neomake/neomake'
" Be able to repeat (using .) plugin operations
Plug 'tpope/vim-repeat'
" Easily surround code with parens, HTML tags, functions, and more
Plug 'tpope/vim-surround'
" Git wrapper plugin
Plug 'tpope/vim-fugitive'
Plug 'shumphrey/fugitive-gitlab.vim'
Plug 'airblade/vim-gitgutter'
" extended % matching for HTML, LaTeX, and many other languages
" Plug 'tmhedberg/matchit'
" Vim's MatchParen for HTML tags
Plug 'gregsexton/MatchTag'
" Easily re-order plugin arguments
Plug 'machakann/vim-swap'
" display the indention levels with thin vertical lines
Plug 'Yggdroot/indentLine'
" Seamless navigation between tmux panes and vim splits
Plug 'christoomey/vim-tmux-navigator'
" insert or delete brackets, parens, quotes in pair
Plug 'jiangmiao/auto-pairs'
Plug 'vim-scripts/taglist.vim'
" Temporarily make the current window full screen
Plug 'troydm/zoomwintab.vim'
" Colorize hex codes and ansi escape sequences
Plug 'chrisbra/Colorizer'

" Base language packages ------------------------

Plug 'vim-scripts/haproxy'
Plug 'vim-scripts/nginx.vim'
Plug 'fatih/vim-go'
Plug 'posva/vim-vue'
Plug 'isRuslan/vim-es6'
Plug 'martinda/Jenkinsfile-vim-syntax'
Plug 'leafgarland/typescript-vim'

" Language augmentation packages ---------------------

Plug 'tpope/vim-fireplace'
" Plug 'tpope/vim-salve'
Plug 'venantius/vim-cljfmt'
" Plug 'clojure-vim/acid.nvim', { 'do': ':UpdateRemotePlugins' }
Plug 'guns/vim-slamhound', { 'for': 'clojure' }
Plug 'guns/vim-sexp', { 'for': 'clojure' }
Plug 'tpope/vim-sexp-mappings-for-regular-people', { 'for': 'clojure' }
Plug 'hashivim/vim-terraform', { 'for': 'terraform' }
Plug 'juliosueiras/vim-terraform-completion', { 'for': 'terraform' }
Plug 'davidhalter/jedi-vim', { 'for': 'python' }
Plug 'Glench/Vim-Jinja2-Syntax'
Plug 'nsf/gocode', { 'for': 'go', 'rtp': 'vim', 'do': '~/.vim/plugged/gocode/vim/symlink.sh' }
Plug 'iamcco/markdown-preview.vim'
Plug 'mpyatishev/vim-sqlformat'

" Colorschemes -------------------------------

Plug 'b-ryan/vim-colors-synthwave'
Plug 'luochen1990/rainbow'
Plug 'srcery-colors/srcery-vim'

call plug#end()


filetype plugin indent on
syntax enable

let mapleader = ","

colorscheme synthwave
" set background=light

" tab settings -------------------------------------------------------------->
set autoindent " Uses indent from current line as indent for new line
set expandtab " Inserts spaces instead of actual tabs
set shiftwidth=4 " The number of columns to use when auto-indenting lines
set tabstop=4 " Determines the number of columns to use when showing actual
              " tab characters
" set softtabstop=4 " Determines the number of columns that will be inserted or
                  " deleted when you hit the tab key. Will use a mixture of
                  " spaces and tabs when expandtab is not set.
set smarttab " Uses the value of shiftwidth when inserting or deleting tabs
             " at the beginnings of lines (in more practical terms, it allows
             " you to treat tabs that were expanded into spaces as tabs, but
             " only when they are at the beginning of a line).
             " When using softtabstop and expand tab, smarttab doesn't need
             " to be used
" From my understand, the fundamental difference between tabstop and
" softtabstop is that tabstop determines the behavior of actual tab characters
" (<Tab>). If neither expandtab nor softtabstop are set, then using the tab
" key will just insert the <Tab> character and use the value of tabstop to
" determine how wide the tab will be.
" On the other hand, softtabstop takes over when the tab key on your keyboard
" is pressed. If your softtabstop is set to 4 and tabstop is set to 8, then
" hitting tab will insert 4 columns for you (the value of softtabstop).
" However, since this isn't enough to be a tab character, it will use spaces
" to achieve those 4 columns.
" <---------------------------------------------------------------------------

" See :help 'option' for details on any option below

set rnu
set bs=2
set laststatus=2
set hidden
set list
set listchars=tab:>\ ,trail:.
set incsearch
set hlsearch
set ignorecase
set smartcase
set mouse=
set splitbelow
set splitright
" set noswapfile
set completeopt=menu,preview
set complete-=t,i
" set colorcolumn=80
set wildmenu
set formatoptions+=j
" set cursorline
" set cursorcolumn
set nojoinspaces
set modeline

set statusline=%f\ %m%r " filename, modified flag, and readonly flag
set statusline+=%= " left/right separator
set statusline+=[%{strlen(&ft)?&ft:'none'}] " filetype
set statusline+=[%{&ff}] " file format (ie. line endings)
set statusline+=[%{strlen(&fenc)?&fenc:'none'}] " encoding
set statusline+=\ \|\ " a separator
set statusline+=col\ %c\  " column number
set statusline+=line\ %l\ of\ %L " line number
" for more about customizing the status bar, see
" http://got-ravings.blogspot.com/2008/08/vim-pr0n-making-statuslines-that-own.html

" autocmd BufEnter * set list " make sure visual whitespace is always shown

set history=2000

" jump to last position on previous close
autocmd BufReadPost *
    \ if line("'\"") > 1 && line("'\"") <= line("$") |
    \   exe "normal! g`\"" |
    \ endif

autocmd FileType php set keywordprg=pman

" Start in insert mode when using the command window. See :help q:
autocmd CmdwinEnter [/?]  startinsert

" general key mappings --------------------------------------------------------

nnoremap <Leader>p :set paste<cr>
nnoremap <Leader>P :set nopaste<cr>
nmap <leader>l :e#<cr>

" Change 'Y' to copy to end of line to be similar to D and C
nnoremap Y y$

" Keys for more efficient saving
nmap <F12> :wa<CR>

" line movement mappings from http://vim.wikia.com/wiki/Moving_lines_up_or_down
" Use Alt-j or Alt-k to move lines up or down, respectively
" The "execute" lines based on: https://stackoverflow.com/a/27206531/683436
if !has('nvim')
    execute "set <M-j>=\ej"
    execute "set <M-k>=\ek"
endif
nnoremap <M-j> :m+<CR>==
inoremap <M-j> <Esc>:m+<CR>==gi
vnoremap <M-j> :m'>+<CR>gv=gv
nnoremap <M-k> :m-2<CR>==
inoremap <M-k> <Esc>:m-2<CR>==gi
vnoremap <M-k> :m-2<CR>gv=gv

" Proper Ctrl+C -> Esc map
map <C-c> <Esc>
imap <C-c> <Esc>

" Remove trailing whitespace
nmap <Leader>w :%s/\s\+$//<CR>

" Will put you insert mode on the next line (like doing just 'o', but will
" also put an extra blank line below this new line.
nnoremap <Leader>o o<esc>O

autocmd BufNewFile,BufRead *.clj,*.c,*.html,*.js,*.coffee,*.json,*.rb,*.tf,*.tfvars,*.vue setlocal shiftwidth=2
autocmd BufNewFile,BufRead Makefile,*.php,*.go setlocal noexpandtab
autocmd BufNewFile,BufRead *.pp,Vagrantfile set filetype=ruby
autocmd BufNewFile,BufRead *.edn set filetype=clojure
autocmd BufNewFile,BufRead *.md set filetype=markdown
autocmd BufNewFile,BufRead *.ino set filetype=c
autocmd BufNewFile,BufRead *.json set filetype=json
autocmd BufEnter * setlocal cursorline
autocmd BufLeave * setlocal nocursorline
autocmd InsertEnter * set nocursorline
autocmd InsertLeave * set cursorline
autocmd BufWritePre * :%s/\s\+$//e

" -----------------------------------------------------------------------------
" from https://stackoverflow.com/a/25327689/683436
" use an orange cursor in insert mode
let &t_SI = "\<Esc>]12;orange\x7"
" use a red cursor otherwise
let &t_EI = "\<Esc>]12;red\x7"

" from https://stackoverflow.com/a/42118416/683436
" Change cursor in insert mode
let &t_SI = "\e[6 q"
let &t_EI = "\e[2 q"


" -----------------------------------------------------------------------------
" Plugin settings and mappings
" -----------------------------------------------------------------------------

" NERDTree settings and mappings
let NERDTreeIgnore=['\.swp$', '\.orig$', '\.pyc$', '\.class$', '__pycache__',
                \   '\.swo$', '\.sass-cache', '\.egg-info', '^node_modules$', '^dist$',
                \   '\local-m2']
let NERDTreeShowHidden=1 " show hidden files
let NERDTreeChDirMode=2 " change directory whenever NERDTree does
let NERDTreeShowLineNumbers=1
let NERDTreeShowBookmarks=1
nnoremap <F5> :NERDTreeToggle<CR>
map <leader>r :NERDTreeFind<CR>

let g:ftplugin_sql_omni_key = '<C-j>'

" bufexplorer ----------------------------------------------------------------
let g:bufExplorerShowRelativePath=1

" ctrlp ----------------------------------------------------------------------
let g:ctrlp_cmd = 'CtrlPLastMode'
let g:ctrlp_custom_ignore = {
    \ 'dir': '\.git$\|\.hg$\|\.venv$\|build$\|\.compiled$\|\.awesomo$\|node_modules$\|bower.*$\|\.cljs_rhino_repl\|target\|\.pelican\.*\|berks-cookbooks\|venv\|local-m2',
    \ 'file': '\.swp$\|\.pyc$\|resources.*compiled',
    \ }
" let g:ctrlp_by_filename = 1 " default to filename search instead of full path
" let g:ctrlp_regexp = 1 " default to regexp search
let g:ctrlp_working_path_mode = 0

" surround -------------------------------------------------------------------
let g:surround_no_insert_mappings = 1

" taglist --------------------------------------------------------------------
let Tlist_Use_Right_Window = 1 " place taglist window on the right
let Tlist_Display_Prototype = 1 " show prototypes instead of tags
" mapping to open taglist
nmap <F7> :TlistToggle<CR>

" UltiSnips ------------------------------------------------------------------
let g:UltiSnipsSnippetDirectories = ["UltiSnips", "bucks_snippets"]
let g:UltiSnipsExpandTrigger = "<c-g>"
let g:UltiSnipsJumpForwardTrigger = "<c-g>"
let g:UltiSnipsJumpBackwardTrigger = "<c-z>"

" neomake --------------------------------------------------------------------
call neomake#configure#automake('w')
let g:neomake_open_list = 2
let g:neomake_python_pep8_exe = 'python3'

" Tagbar ---------------------------------------------------------------------
let g:tagbar_type_haskell = {
    \ 'ctagsbin'  : 'hasktags',
    \ 'ctagsargs' : '-x -c -o-',
    \ 'kinds'     : [
        \  'm:modules:0:1',
        \  'd:data: 0:1',
        \  'd_gadt: data gadt:0:1',
        \  't:type names:0:1',
        \  'nt:new types:0:1',
        \  'c:classes:0:1',
        \  'cons:constructors:1:1',
        \  'c_gadt:constructor gadt:1:1',
        \  'c_a:constructor accessors:1:1',
        \  'ft:function types:1:1',
        \  'fi:function implementations:0:1',
        \  'o:others:0:1'
    \ ],
    \ 'sro'        : '.',
    \ 'kind2scope' : {
        \ 'm' : 'module',
        \ 'c' : 'class',
        \ 'd' : 'data',
        \ 't' : 'type'
    \ },
    \ 'scope2kind' : {
        \ 'module' : 'm',
        \ 'class'  : 'c',
        \ 'data'   : 'd',
        \ 'type'   : 't'
    \ }
\ }

" indentLine -----------------------------------------------------------------
let g:indentLine_fileType = ['json']
let g:indentLine_char = '⎸'
let g:indentLine_concealcursor = ""

" vim-tmux-navigator ---------------------------------------------------------
let g:tmux_navigator_no_mappings = 1
nnoremap <silent> <c-h> :TmuxNavigateLeft<cr>
nnoremap <silent> <c-j> :TmuxNavigateDown<cr>
nnoremap <silent> <c-k> :TmuxNavigateUp<cr>
nnoremap <silent> <c-n> :TmuxNavigateRight<cr>
nnoremap <silent> <c-\> :TmuxNavigatePrevious<cr>

" more tmux integration
nmap <leader>. :!tmux send-keys -t :0.1 C-p C-j <CR><CR>

function! ClojureClasspath()
    let l:classpath = system("lein classpath")
    let g:JavaComplete_LibsPath = l:classpath
endfunction

" jedi -----------------------------------------------------------------------
let g:jedi#rename_command = ""

" terraform ------------------------------------------------------------------
let g:terraform_fold_sections = 1
let g:terraform_remap_spacebar = 1
let g:terraform_fmt_on_save = 1
autocmd FileType terraform setlocal commentstring=#%s

let g:clj_fmt_autosave = 0


let g:rainbow_active = 1

" vim-fireplace - run test under expression
nmap cps :.RunTests<cr>
